Update for JupyterLab 3
I added the jlab buildutils update dependency script, so I could just run this:

jlpm run update-dependency --regex "^@jupyterlab/"
jlpm run update-dependency --regex "^typescript$" '~latest'


I reverted the Typescript upgrade for vega3 since it had the following error when compiling with Typescript 3.7 or above:

../../node_modules/vega-lite/build/src/compile/selection/selection.d.ts(11,10): error TS2440: Import declaration conflicts with local declaration of 'SelectionComponent'.